# Generated by Django 3.2 on 2021-10-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_title_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
